services:
  test-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: hackathon-test-db
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_postgres_data:
    driver: local