services:
  test-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: hackathon-test-db
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hackathon-api-test
    env_file:
      - .env.test
    depends_on:
      test-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: test-db
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@test-db:5432/${POSTGRES_DB}

volumes:
  test_postgres_data:
    driver: local
